import { execFileSync } from 'node:child_process';
import {
  appendFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';

interface SetupPayload {
  repository: string;
  publisherRef: string;
  maintainers: string[];
  config: { schemaVersion: 1; id: string } & Record<string, unknown>;
}

const workspace = resolve(process.env.GITHUB_WORKSPACE || '.');
const run = (command: string, args: string[]) =>
  execFileSync(command, args, { cwd: workspace, stdio: 'inherit' });
const payload = JSON.parse(
  Buffer.from(process.env.VANAHUB_SETUP || '', 'base64').toString('utf8'),
) as SetupPayload;
if (
  payload.repository.toLowerCase() !==
  (process.env.GITHUB_REPOSITORY || '').toLowerCase()
)
  throw new Error(
    'Setup payload repository does not match the workflow repository.',
  );
if (!/^[a-z0-9][a-z0-9._-]{1,63}$/.test(payload.config.id))
  throw new Error('Invalid setup package ID.');
if (!/^[0-9a-f]{40}$/.test(payload.publisherRef))
  throw new Error('Publisher automation must be pinned to a full commit SHA.');
if (!payload.maintainers.length)
  throw new Error('At least one maintainer is required.');

const branch = `vanahub/setup-${payload.config.id}`;
const base = process.env.GITHUB_REF_NAME || 'main';
run('git', ['config', 'user.name', 'github-actions[bot]']);
run('git', [
  'config',
  'user.email',
  '41898282+github-actions[bot]@users.noreply.github.com',
]);
run('git', ['switch', '-C', branch, `origin/${base}`]);

const packagePath = resolve(workspace, '.vanahub/package.json');
mkdirSync(dirname(packagePath), { recursive: true });
writeFileSync(packagePath, `${JSON.stringify(payload.config, null, 2)}\n`);
const authorizationPath = resolve(workspace, '.vanahub.json');
const authorization = existsSync(authorizationPath)
  ? JSON.parse(readFileSync(authorizationPath, 'utf8'))
  : { schemaVersion: 1, packages: {} };
if (authorization.schemaVersion !== 1 || !authorization.packages)
  throw new Error('Existing .vanahub.json is unsupported.');
authorization.packages[payload.config.id] = {
  maintainers: payload.maintainers,
};
writeFileSync(authorizationPath, `${JSON.stringify(authorization, null, 2)}\n`);

run('git', ['add', '.vanahub.json', '.vanahub/package.json']);
const changed = execFileSync('git', ['status', '--porcelain'], {
  cwd: workspace,
  encoding: 'utf8',
}).trim();
if (!changed) process.exit(0);
run('git', [
  'commit',
  '-m',
  `Set up VanaHub publishing for ${payload.config.id}`,
]);
run('git', ['push', '--force-with-lease', '--set-upstream', 'origin', branch]);
try {
  run('gh', [
    'pr',
    'create',
    '--base',
    base,
    '--head',
    branch,
    '--title',
    `Set up VanaHub publishing for ${payload.config.id}`,
    '--body',
    'Generated by VanaHub Publisher. Review the package metadata and maintainer authorization before merging.',
  ]);
} catch {
  try {
    run('gh', ['pr', 'view', branch, '--web=false']);
  } catch {
    const compareUrl = `https://github.com/${payload.repository}/compare/${encodeURIComponent(base)}...${encodeURIComponent(branch)}?expand=1`;
    console.log(
      `GitHub did not allow Actions to create the pull request. Open ${compareUrl}`,
    );
    if (process.env.GITHUB_STEP_SUMMARY)
      appendFileSync(
        process.env.GITHUB_STEP_SUMMARY,
        `## Finish setup\n\n[Open the generated setup pull request](${compareUrl}).\n`,
      );
  }
}
