import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';

interface SetupPayload {
  repository: string;
  publisherRef: string;
  maintainers: string[];
  config: { schemaVersion: 1; id: string } & Record<string, unknown>;
}

const workspace = resolve(process.env.GITHUB_WORKSPACE || '.');
const run = (command: string, args: string[]) =>
  execFileSync(command, args, { cwd: workspace, stdio: 'inherit' });
const payload = JSON.parse(
  Buffer.from(process.env.VANAHUB_SETUP || '', 'base64').toString('utf8'),
) as SetupPayload;
if (
  payload.repository.toLowerCase() !==
  (process.env.GITHUB_REPOSITORY || '').toLowerCase()
)
  throw new Error(
    'Setup payload repository does not match the workflow repository.',
  );
if (!/^[a-z0-9][a-z0-9._-]{1,63}$/.test(payload.config.id))
  throw new Error('Invalid setup package ID.');
if (!/^[0-9a-f]{40}$/.test(payload.publisherRef))
  throw new Error('Publisher automation must be pinned to a full commit SHA.');
if (!payload.maintainers.length)
  throw new Error('At least one maintainer is required.');

const branch = `vanahub/setup-${payload.config.id}`;
const base = process.env.GITHUB_REF_NAME || 'main';
run('git', ['config', 'user.name', 'github-actions[bot]']);
run('git', [
  'config',
  'user.email',
  '41898282+github-actions[bot]@users.noreply.github.com',
]);
run('git', ['switch', '-C', branch, `origin/${base}`]);

const packagePath = resolve(workspace, '.vanahub/package.json');
mkdirSync(dirname(packagePath), { recursive: true });
writeFileSync(packagePath, `${JSON.stringify(payload.config, null, 2)}\n`);
const authorizationPath = resolve(workspace, '.vanahub.json');
const authorization = existsSync(authorizationPath)
  ? JSON.parse(readFileSync(authorizationPath, 'utf8'))
  : { schemaVersion: 1, packages: {} };
if (authorization.schemaVersion !== 1 || !authorization.packages)
  throw new Error('Existing .vanahub.json is unsupported.');
authorization.packages[payload.config.id] = {
  maintainers: payload.maintainers,
};
writeFileSync(authorizationPath, `${JSON.stringify(authorization, null, 2)}\n`);

const releaseWorkflow = `name: Publish VanaHub addon

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: \${{ github.event.release.tag_name }}
      - id: package
        uses: Hildaware/vanahub-publisher@${payload.publisherRef}
      - name: Attach VanaHub assets
        env:
          GH_TOKEN: \${{ github.token }}
          VH_TAG: \${{ github.event.release.tag_name }}
          VH_OUTPUT: \${{ steps.package.outputs.output-directory }}
        run: gh release upload "$VH_TAG" "$VH_OUTPUT"/* --clobber
      - name: Catalog submission
        env:
          VH_ID: \${{ steps.package.outputs.package-id }}
          VH_REPOSITORY: \${{ github.repository }}
        run: |
          url="https://github.com/Hildaware/vanahub-catalog/issues/new?template=vanahub-submission.yml&repository=https%3A%2F%2Fgithub.com%2F\${VH_REPOSITORY}&package_id=\${VH_ID}"
          echo "### Catalog" >> "$GITHUB_STEP_SUMMARY"
          echo "For first admission, [submit this release to VanaHub](\${url}). Later releases are discovered automatically." >> "$GITHUB_STEP_SUMMARY"
`;
const releasePath = resolve(workspace, '.github/workflows/vanahub-release.yml');
mkdirSync(dirname(releasePath), { recursive: true });
writeFileSync(releasePath, releaseWorkflow);
rmSync(resolve(workspace, '.github/workflows/vanahub-setup.yml'), {
  force: true,
});

run('git', [
  'add',
  '.vanahub.json',
  '.vanahub/package.json',
  '.github/workflows/vanahub-release.yml',
  '.github/workflows/vanahub-setup.yml',
]);
const changed = execFileSync('git', ['status', '--porcelain'], {
  cwd: workspace,
  encoding: 'utf8',
}).trim();
if (!changed) process.exit(0);
run('git', [
  'commit',
  '-m',
  `Set up VanaHub publishing for ${payload.config.id}`,
]);
run('git', ['push', '--force-with-lease', '--set-upstream', 'origin', branch]);
try {
  run('gh', [
    'pr',
    'create',
    '--base',
    base,
    '--head',
    branch,
    '--title',
    `Set up VanaHub publishing for ${payload.config.id}`,
    '--body',
    'Generated by VanaHub Publisher. Review the package metadata, maintainer authorization, and pinned release workflow before merging.',
  ]);
} catch {
  run('gh', ['pr', 'view', branch, '--web=false']);
}
